INSERT INTO PETS (ID, NAME, DESCRIPTION, AGE) VALUES (2001, 'Tom','German Shepherd', 3);
INSERT INTO PETS (ID, NAME, DESCRIPTION, AGE) VALUES (2002, 'Emily','Serbian Husky', 2);
INSERT INTO PETS (ID, NAME, DESCRIPTION, AGE) VALUES (2003, 'Catherine','Siamese Cat', 4);
INSERT INTO PETS (ID, NAME, DESCRIPTION, AGE) VALUES (2004, 'Richard','Persian Cat', 1);
COMMIT;
