extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  influxdb:
    endpoint: 0.0.0.0:8086
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [ otlp, jaeger ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp, prometheus, influxdb ]
      exporters: [ debug ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug ]
  extensions: [ health_check, pprof, zpages ]